----
   title: "Twitter Analysis"
   author: "Joel Soroos"
   date: "January 7, 2020"
   output: html_document 
---


### 1a. Source tweets
```{r source, warning = TRUE, results = FALSE, message = FALSE}

   library (tidyverse)
   library (rtweet)

   tweets_raw <- get_timeline("soroosj", n=1000)
```


###1b. Source followers
```{r}

   followers <- "soroosj" %>%
      get_followers() %>%
      pull (user_id) %>%
      lookup_users () %>%
      select (user_id, screen_name, name, location, followers_count:favourites_count)
```


###1c. Source friends
```{r}

   friends <- "soroosj" %>%
      get_friends() %>%
      pull (user_id) %>%
      lookup_users () %>%
      select (user_id, screen_name, name, location, followers_count:favourites_count)
```
 
   
### 2. Transform timeline
```{r transform, message = F}

  library (lubridate)

   tweets <- tweets_raw %>%
      filter (is_retweet == FALSE) %>%
      rename (
         likes = favorite_count,
         retweets = retweet_count,
         created = created_at
         ) %>%
      mutate (
         text_length = str_length(text),
         text = str_sub(text,1,60),
         created = as.Date(created),
         year = year(created)
         ) %>% 
      filter(
         is_retweet == FALSE
         ) %>%
      select (text, year, likes, retweets, created)
```


### 3a. Visualize - top likes
```{r chart_likes, warning = TRUE, message = FALSE}

   library (gt)

   tweets %>%
      arrange (-likes, -retweets) %>%
      head (10) %>%
      rowid_to_column("rank") %>%
      select (-year) %>%
      relocate (rank) %>%
      gt () 
```


### 3b. Visualize - top retweets
```{r chart_retweet, warning = TRUE, message = FALSE}

   tweets %>%
      arrange (-retweets, -likes) %>%
      head (10) %>%
      rowid_to_column("rank") %>%
      select (rank, text, retweets, likes, created) %>%
      gt ()
```


### 3c. Visualize - by year
```{r chart_year}

   tweets %>%
      group_by (year) %>%
      summarize (
         n = n (),
         likes = sum(likes),
         retweets = sum (retweets)
         ) %>%
      mutate(likes_per_tweet = round(likes/n,2)) %>%
      arrange (-year) %>%
      gt () 
```