----
   title: "Twitter Analysis"
   author: "Joel Soroos"
   date: "November 2, 2020"
   output: html_document 
---


### 1a. Source tweets
```{r source, warning = TRUE, results = FALSE, message = FALSE}

   library (rtweet)
   library (tidyverse)
   library (lubridate)

   tweets_raw <- get_timeline ("soroosj")

   tweets <- tweets_raw %>%
      filter (is_retweet == FALSE) %>%
      rename (
         likes = favorite_count,
         retweets = retweet_count,
         created = created_at
         ) %>%
      mutate (
         text_length = str_length(text),
         text = str_sub(text,1,60),
         created = as.Date(created),
         year = year(created)
         ) %>%
      select (text, year, likes, retweets, created)
```




### 2a. Visualize - top liked tweets
```{r chart_likes, warning = TRUE, message = FALSE}

   library (gt)

   tweets %>%
      arrange (-likes, -retweets) %>%
      head (10) %>%
      rowid_to_column("rank") %>%
      select (-year) %>%
      relocate (rank) %>%
      gt () 
```


### 2b. Visualize - top retweets
```{r chart_retweet, warning = TRUE, message = FALSE}

   tweets %>%
      arrange (-retweets, -likes) %>%
      head (10) %>%
      rowid_to_column("rank") %>%
      select (rank, text, retweets, likes, created) %>%
      gt ()
```


### 2c. Visualize - tweets by year
```{r chart_year}

   tweets %>%
      group_by (year) %>%
      summarize (
         n = n (),
         likes = sum(likes),
         retweets = sum (retweets)
         ) %>%
      mutate(likes_per_tweet = round(likes/n,2)) %>%
      arrange (-year) %>%
      gt () 
```


###3a. Source followers
```{r}

  followers <- "soroosj" %>%
      get_followers() %>%
      pull (user_id) %>%
      lookup_users () %>%
      select (screen_name, name, location, followers_count) %>%
      arrange (-followers_count) %>%
      rowid_to_column("rank")
```


### 3b.  Visualize - top followers
```{r}

   followers %>%
      head (10) %>%
      select (rank, name, location, followers_count) %>%
      gt () %>%
         fmt_number (columns = vars(followers_count), use_seps = T, decimals = 0)
```


###3c.  Geographic distribution of followers
Twitter provides a location for each user which can be converted using the Google Maps API to geographic coordinates for mapping.  
```{r message = F}
library (ggmap)

   register_google(key = Sys.getenv("GOOGLE_MAPS_API"))

   followers_geo <- followers %>%
      head (15) %>%
      mutate_geocode (location, output = "more") %>%
      mutate (country = word (address, -1,-1)) %>%
      select (rank:followers_count, country, lon, lat) 
```


#3d.  by country
```{r message = F}

   ggplot (followers_geo, aes (x = reorder(country, followers_count), y = followers_count)) +
      geom_col () +
      coord_flip () +
      theme_minimal()
```


#3e.  map
```{r}
   
   library (maps)

   world <- map_data ("world")

   ggplot () +
      geom_map (data = world, map = world, aes (long, lat, map_id = region), fill = "lightgray", color = "black", size =0.05) +
      geom_point (data = followers_geo, aes (x = lon, y = lat), color = "blue", size = 0.75) + 
      theme_classic ()
```